services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    # NO volumes mount - use files from Docker image
    networks:
      - symfony_network
    depends_on:
      - mysql
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://symfony_user:symfony_pass@mysql:3306/symfony_db?serverVersion=8.0&charset=utf8mb4

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      # Mount nginx config
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # Share PHP container's files via volumes_from
    volumes_from:
      - php:ro
    networks:
      - symfony_network
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-symfony_db}
      MYSQL_USER: ${MYSQL_USER:-symfony_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-symfony_pass}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge

volumes:
  mysql_data:

